/**
 * A picture, resampled onto a lattice of dots.
 *
 * The oldest trick in reproduction and still the most useful one here, because
 * of what it throws away. A halftone keeps the silhouette and discards
 * everything else — line weight, interior detail, the drawing's own opinions —
 * which is exactly the compression that makes a figure read as *alive* rather
 * than as a picture of something. It is also, mechanically, the cheapest way a
 * vector renderer can carry a photograph: a few hundred circles on a grid.
 *
 * This is a strictly simpler cousin of `trace`. Where that one has to find
 * centrelines, measure widths and decide what is a limb, this one asks a single
 * question per cell — how much ink is in here — and `coverage` already answers
 * it. Which means the figures come out *measured*, the way this project insists
 * everything is measured, rather than eyeballed onto a grid by hand.
 *
 * Two knobs matter and they trade against each other. Too coarse and the figure
 * is noise; too fine and it stops being a halftone and becomes a picture again.
 * There is no rule for where the line is, which is why `heron match` gets to
 * keep its job here: render the dots, compare against the source, and the
 * overlap score says whether the horse still reads as a horse.
 */

import { round } from './num.ts';
import { type Bitmap, coverage, loadImage } from './raster.ts';

export interface Dot {
  x: number;
  y: number;
  /** Ink in this cell, 0 to 1. Drive the radius with it, or ignore it. */
  weight: number;
}

/** One frame's worth of dots, with the box they were sampled from. */
export interface Plate {
  dots: Dot[];
  width: number;
  height: number;
  /** Spacing of the lattice, in the same units as the dots. */
  pitch: number;
}

export interface HalftoneOptions {
  /** Cells across the image's width. This is the one number that matters. */
  across: number;
  /** Ink below this leaves the cell empty. */
  threshold?: number;
  /**
   * Offset alternate rows by half a cell.
   *
   * A square lattice announces itself: the eye finds the columns before it finds
   * the figure. Half-offsetting the rows is the cheap half of what a real
   * halftone screen does by rotating, and it costs one addition.
   */
  stagger?: boolean;
  /** Width of the output box. Dots are placed inside it; defaults to pixels. */
  width?: number;
}

/**
 * Samples a bitmap onto a lattice.
 *
 * Cell coverage is the mean over the whole cell rather than the value at its
 * centre, which is the difference between a figure that survives a thin limb and
 * one that drops it whenever the limb happens to fall between two sample points.
 */
export function halftone(bm: Bitmap, o: HalftoneOptions): Plate {
  const across = Math.max(1, Math.round(o.across));
  const threshold = o.threshold ?? 0.15;
  const cov = coverage(bm);

  const cell = bm.width / across;
  const down = Math.max(1, Math.round(bm.height / cell));
  const scale = (o.width ?? bm.width) / bm.width;
  const pitch = cell * scale;

  const dots: Dot[] = [];
  for (let row = 0; row < down; row++) {
    const shift = o.stagger && row % 2 ? 0.5 : 0;
    for (let col = 0; col < across; col++) {
      const cx = (col + 0.5 + shift) * cell;
      const cy = (row + 0.5) * cell;

      let sum = 0;
      let n = 0;
      const x0 = Math.max(0, Math.floor(cx - cell / 2));
      const x1 = Math.min(bm.width, Math.ceil(cx + cell / 2));
      const y0 = Math.max(0, Math.floor(cy - cell / 2));
      const y1 = Math.min(bm.height, Math.ceil(cy + cell / 2));
      for (let y = y0; y < y1; y++) {
        for (let x = x0; x < x1; x++) {
          sum += cov.data[y * bm.width + x];
          n++;
        }
      }
      const weight = n ? sum / n : 0;
      if (weight >= threshold) dots.push({ x: cx * scale, y: cy * scale, weight });
    }
  }
  return { dots, width: bm.width * scale, height: bm.height * scale, pitch };
}

/** The same, from a file. */
export function halftoneFile(file: string, o: HalftoneOptions): Plate {
  return halftone(loadImage(file), o);
}

/**
 * The plates as a TypeScript module.
 *
 * Emitted rather than sampled at scene-build time for the same reason `trace`
 * emits: a scene that re-read a dozen PNGs on every `lint`, `sheet` and `build`
 * would pay seconds for an answer that cannot change, and would stop being
 * readable as a description of the film. The measurement happens once and the
 * numbers become source.
 */
export function plateSource(plates: Plate[], name = 'PLATES'): string {
  const one = (p: Plate) =>
    `  { pitch: ${round(p.pitch, 1)}, width: ${round(p.width, 1)}, height: ${round(p.height, 1)}, dots: [\n`
    + chunk(p.dots.map((d) => `[${round(d.x, 1)},${round(d.y, 1)},${round(d.weight, 2)}]`))
    + '\n  ] },';

  return `// Generated by \`heron halftone\`. Each dot is [x, y, ink].
export interface Plate { pitch: number; width: number; height: number; dots: [number, number, number][] }

export const ${name}: Plate[] = [
${plates.map(one).join('\n')}
];
`;
}


/** Wraps a long list so the generated file is readable and diffs sanely. */
function chunk(items: string[], per = 6): string {
  const lines: string[] = [];
  for (let i = 0; i < items.length; i += per) lines.push('    ' + items.slice(i, i + per).join(', '));
  return lines.join(',\n');
}
